#! /bin/sh

regexps="(^\s+(it|describe).*(focus:|:focus\s*=>)\s*true|\@focus)"

git grep --cached -n -E "${regexps}" && (
    echo "It seems you left focused specs/scenarios. You should remove focus tags."
    exit 1
)
