#! /bin/sh

export focus_matched=0

if git grep --cached -n -E "^\s+(it|describe).*(focus:|:focus\s*=>)\s*true" -- '*_spec.rb';
then
    echo "It seems you left focused specs. You should remove focus tags.";
    focus_matched=1
fi

if git grep --cached -n "@focus" -- '*.feature';
then
    echo "It seems you left focused cucumber scenarios. You should remove focus tags.";
    focus_matched=1
fi

exit $focus_matched
